import { Inter } from 'next/font/google';
import React from 'react';

import { Header } from './ui-domain/Header';

import type { Metadata } from 'next';

import './styles/svg.scss';
import './styles/size.scss';
import './styles/color.scss';
import './styles/global.scss';
import './styles/variables.scss';
import './styles/typography.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: ' ゆめみフロントエンドコーディングテスト',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
