name: Jest & Playwright

# タイミングを指定
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Test:
    name: Run test codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and cache nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install packages
        run: npm install
      - name: Set up Playwright
        run: npx playwright install  
      - name: Show coverage
        run: npm run test --maxWorkers=100% --watchAll=false --coverage
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_RESAS_API_URL: ${{ secrets.NEXT_PUBLIC_RESAS_API_URL }}
          NEXT_PUBLIC_RESAS_API_KEY: ${{ secrets.NEXT_PUBLIC_RESAS_API_KEY }}